@startuml

left to right direction

actor Estudante

rectangle "Sistema StudyMate" {

    usecase "Cadastrar usuário" as UC01
    usecase "Realizar login" as UC02
    usecase "Visualizar agenda acadêmica" as UC03
    usecase "Gerenciar período letivo" as UC04
    usecase "Gerenciar disciplinas" as UC05
    usecase "Gerenciar horários de aula" as UC06

    usecase "Gerenciar tarefas" as UC07
    usecase "Concluir tarefa" as UC07A
    usecase "Reagendar tarefa" as UC07B

    usecase "Gerenciar avaliações" as UC08

    usecase "Registrar faltas" as UC10

    usecase "Consultar notificações" as UC12
    usecase "Marcar notificação\ncomo lida" as UC12A

    usecase "Acompanhar progresso" as UC13
    usecase "Consultar conquistas" as UC14
    usecase "Gerenciar perfil" as UC15


    ' Força os extends para a direita
    UC07 -[hidden]right-> UC07A
    UC07A -[hidden]down-> UC07B

    UC12 -[hidden]right-> UC12A
}

Estudante -- UC01
Estudante -- UC02
Estudante -- UC03
Estudante -- UC04
Estudante -- UC05
Estudante -- UC06
Estudante -- UC07
Estudante -- UC08
Estudante -- UC10
Estudante -- UC12
Estudante -- UC13
Estudante -- UC14
Estudante -- UC15


' EXTENDS
' A seta continua apontando para o caso de uso base

UC07A ..> UC07 : <<extend>>
UC07B ..> UC07 : <<extend>>

UC12A ..> UC12 : <<extend>>

@enduml